//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_serialization.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#include "duckdb/common/serializer/serializer.hpp"
#include "duckdb/common/serializer/deserializer.hpp"
#include "duckdb/catalog/dependency.hpp"
#include "duckdb/catalog/dependency_set.hpp"

namespace duckdb {

void CatalogEntryInfo::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<CatalogType>(100, "type", type);
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	serializer.WritePropertyWithDefault<Identifier>(102, "name", name);
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<vector<Identifier>>(103, "schema_path", schema_path, vector<Identifier>());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(104, "parent_name", parent_name, Identifier());
	}
}

CatalogEntryInfo CatalogEntryInfo::Deserialize(Deserializer &deserializer) {
	CatalogEntryInfo result;
	deserializer.ReadProperty<CatalogType>(100, "type", result.type);
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	deserializer.ReadPropertyWithDefault<Identifier>(102, "name", result.name);
	deserializer.ReadPropertyWithExplicitDefault<vector<Identifier>>(103, "schema_path", result.schema_path, vector<Identifier>());
	deserializer.ReadPropertyWithExplicitDefault<Identifier>(104, "parent_name", result.parent_name, Identifier());
	if (result.schema_path.empty() && result.type != CatalogType::SCHEMA_ENTRY && !schema.empty()) {
		result.schema_path.push_back(std::move(schema));
	}
	return result;
}

void LogicalDependency::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<CatalogEntryInfo>(100, "entry", entry);
	serializer.WritePropertyWithDefault<Identifier>(101, "catalog", catalog);
}

LogicalDependency LogicalDependency::Deserialize(Deserializer &deserializer) {
	auto entry = deserializer.ReadProperty<CatalogEntryInfo>(100, "entry");
	auto catalog = deserializer.ReadPropertyWithDefault<Identifier>(101, "catalog");
	LogicalDependency result(deserializer.TryGet<Catalog>(), entry, std::move(catalog));
	return result;
}

void LogicalDependencySet::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<dependency_set_t>(100, "set", set);
}

LogicalDependencySet LogicalDependencySet::Deserialize(Deserializer &deserializer) {
	LogicalDependencySet result;
	deserializer.ReadProperty<dependency_set_t>(100, "set", result.set);
	return result;
}

} // namespace duckdb
